# @format

apiVersion: v1
kind: Service
metadata:
  name: auth-nodeport-srv
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 32220
